package catalog

import "strings"

type SceneBlueprint struct {
	ID        string `json:"id"`
	Genre     string `json:"genre"`
	Phase     string `json:"phase"`
	Goal      string `json:"goal"`
	Conflict  string `json:"conflict"`
	Checklist string `json:"checklist"`
}

var sceneBlueprints = []SceneBlueprint{
	{
		ID:        "blueprint-001",
		Genre:     "drama",
		Phase:     "opening-image",
		Goal:      "用可视化日常建立主人公当前秩序，突出关系抉择",
		Conflict:  "展示尚未解决的核心缺口，形成真实代价",
		Checklist: "让环境细节暗示主题",
	},
	{
		ID:        "blueprint-002",
		Genre:     "drama",
		Phase:     "inciting-event",
		Goal:      "用不可逆事件打破原有平衡，突出关系抉择",
		Conflict:  "迫使主人公回应外部变化，形成真实代价",
		Checklist: "确保事件与核心欲望相关",
	},
	{
		ID:        "blueprint-003",
		Genre:     "drama",
		Phase:     "debate",
		Goal:      "让主人公比较行动与逃避的代价，突出关系抉择",
		Conflict:  "通过关系冲突暴露恐惧，形成真实代价",
		Checklist: "建立进入新局面的必要性",
	},
	{
		ID:        "blueprint-004",
		Genre:     "drama",
		Phase:     "threshold",
		Goal:      "让主人公做出明确且可见的选择，突出关系抉择",
		Conflict:  "改变地点关系或行动规则，形成真实代价",
		Checklist: "给予选择即时后果",
	},
	{
		ID:        "blueprint-005",
		Genre:     "drama",
		Phase:     "progress",
		Goal:      "用连续行动检验主人公的方法，突出关系抉择",
		Conflict:  "同步推进目标与关系压力，形成真实代价",
		Checklist: "让每次得失改变下一步",
	},
	{
		ID:        "blueprint-006",
		Genre:     "drama",
		Phase:     "midpoint",
		Goal:      "制造改变目标理解的重大结果，突出关系抉择",
		Conflict:  "提升公开风险或私人风险，形成真实代价",
		Checklist: "把主题问题转化为行动",
	},
	{
		ID:        "blueprint-007",
		Genre:     "drama",
		Phase:     "pressure",
		Goal:      "让对手与内在缺陷同时收紧，突出关系抉择",
		Conflict:  "减少可用资源与退路，形成真实代价",
		Checklist: "迫使关系承担剧情功能",
	},
	{
		ID:        "blueprint-008",
		Genre:     "drama",
		Phase:     "crisis",
		Goal:      "让旧方法彻底失效并暴露代价，突出关系抉择",
		Conflict:  "要求主人公承认真实需求，形成真实代价",
		Checklist: "把最终选择准备充分",
	},
	{
		ID:        "blueprint-009",
		Genre:     "drama",
		Phase:     "climax",
		Goal:      "用主动选择解决核心对抗，突出关系抉择",
		Conflict:  "让能力成长体现在行动中，形成真实代价",
		Checklist: "回收关键伏笔与关系承诺",
	},
	{
		ID:        "blueprint-010",
		Genre:     "drama",
		Phase:     "resolution",
		Goal:      "展示新秩序及其具体差异，突出关系抉择",
		Conflict:  "交代主要关系的最终状态，形成真实代价",
		Checklist: "用末尾意象回应开场",
	},
	{
		ID:        "blueprint-011",
		Genre:     "comedy",
		Phase:     "opening-image",
		Goal:      "用可视化日常建立主人公当前秩序，突出误会升级",
		Conflict:  "展示尚未解决的核心缺口，形成情感诚意",
		Checklist: "让环境细节暗示主题",
	},
	{
		ID:        "blueprint-012",
		Genre:     "comedy",
		Phase:     "inciting-event",
		Goal:      "用不可逆事件打破原有平衡，突出误会升级",
		Conflict:  "迫使主人公回应外部变化，形成情感诚意",
		Checklist: "确保事件与核心欲望相关",
	},
	{
		ID:        "blueprint-013",
		Genre:     "comedy",
		Phase:     "debate",
		Goal:      "让主人公比较行动与逃避的代价，突出误会升级",
		Conflict:  "通过关系冲突暴露恐惧，形成情感诚意",
		Checklist: "建立进入新局面的必要性",
	},
	{
		ID:        "blueprint-014",
		Genre:     "comedy",
		Phase:     "threshold",
		Goal:      "让主人公做出明确且可见的选择，突出误会升级",
		Conflict:  "改变地点关系或行动规则，形成情感诚意",
		Checklist: "给予选择即时后果",
	},
	{
		ID:        "blueprint-015",
		Genre:     "comedy",
		Phase:     "progress",
		Goal:      "用连续行动检验主人公的方法，突出误会升级",
		Conflict:  "同步推进目标与关系压力，形成情感诚意",
		Checklist: "让每次得失改变下一步",
	},
	{
		ID:        "blueprint-016",
		Genre:     "comedy",
		Phase:     "midpoint",
		Goal:      "制造改变目标理解的重大结果，突出误会升级",
		Conflict:  "提升公开风险或私人风险，形成情感诚意",
		Checklist: "把主题问题转化为行动",
	},
	{
		ID:        "blueprint-017",
		Genre:     "comedy",
		Phase:     "pressure",
		Goal:      "让对手与内在缺陷同时收紧，突出误会升级",
		Conflict:  "减少可用资源与退路，形成情感诚意",
		Checklist: "迫使关系承担剧情功能",
	},
	{
		ID:        "blueprint-018",
		Genre:     "comedy",
		Phase:     "crisis",
		Goal:      "让旧方法彻底失效并暴露代价，突出误会升级",
		Conflict:  "要求主人公承认真实需求，形成情感诚意",
		Checklist: "把最终选择准备充分",
	},
	{
		ID:        "blueprint-019",
		Genre:     "comedy",
		Phase:     "climax",
		Goal:      "用主动选择解决核心对抗，突出误会升级",
		Conflict:  "让能力成长体现在行动中，形成情感诚意",
		Checklist: "回收关键伏笔与关系承诺",
	},
	{
		ID:        "blueprint-020",
		Genre:     "comedy",
		Phase:     "resolution",
		Goal:      "展示新秩序及其具体差异，突出误会升级",
		Conflict:  "交代主要关系的最终状态，形成情感诚意",
		Checklist: "用末尾意象回应开场",
	},
	{
		ID:        "blueprint-021",
		Genre:     "thriller",
		Phase:     "opening-image",
		Goal:      "用可视化日常建立主人公当前秩序，突出危险逼近",
		Conflict:  "展示尚未解决的核心缺口，形成信息反转",
		Checklist: "让环境细节暗示主题",
	},
	{
		ID:        "blueprint-022",
		Genre:     "thriller",
		Phase:     "inciting-event",
		Goal:      "用不可逆事件打破原有平衡，突出危险逼近",
		Conflict:  "迫使主人公回应外部变化，形成信息反转",
		Checklist: "确保事件与核心欲望相关",
	},
	{
		ID:        "blueprint-023",
		Genre:     "thriller",
		Phase:     "debate",
		Goal:      "让主人公比较行动与逃避的代价，突出危险逼近",
		Conflict:  "通过关系冲突暴露恐惧，形成信息反转",
		Checklist: "建立进入新局面的必要性",
	},
	{
		ID:        "blueprint-024",
		Genre:     "thriller",
		Phase:     "threshold",
		Goal:      "让主人公做出明确且可见的选择，突出危险逼近",
		Conflict:  "改变地点关系或行动规则，形成信息反转",
		Checklist: "给予选择即时后果",
	},
	{
		ID:        "blueprint-025",
		Genre:     "thriller",
		Phase:     "progress",
		Goal:      "用连续行动检验主人公的方法，突出危险逼近",
		Conflict:  "同步推进目标与关系压力，形成信息反转",
		Checklist: "让每次得失改变下一步",
	},
	{
		ID:        "blueprint-026",
		Genre:     "thriller",
		Phase:     "midpoint",
		Goal:      "制造改变目标理解的重大结果，突出危险逼近",
		Conflict:  "提升公开风险或私人风险，形成信息反转",
		Checklist: "把主题问题转化为行动",
	},
	{
		ID:        "blueprint-027",
		Genre:     "thriller",
		Phase:     "pressure",
		Goal:      "让对手与内在缺陷同时收紧，突出危险逼近",
		Conflict:  "减少可用资源与退路，形成信息反转",
		Checklist: "迫使关系承担剧情功能",
	},
	{
		ID:        "blueprint-028",
		Genre:     "thriller",
		Phase:     "crisis",
		Goal:      "让旧方法彻底失效并暴露代价，突出危险逼近",
		Conflict:  "要求主人公承认真实需求，形成信息反转",
		Checklist: "把最终选择准备充分",
	},
	{
		ID:        "blueprint-029",
		Genre:     "thriller",
		Phase:     "climax",
		Goal:      "用主动选择解决核心对抗，突出危险逼近",
		Conflict:  "让能力成长体现在行动中，形成信息反转",
		Checklist: "回收关键伏笔与关系承诺",
	},
	{
		ID:        "blueprint-030",
		Genre:     "thriller",
		Phase:     "resolution",
		Goal:      "展示新秩序及其具体差异，突出危险逼近",
		Conflict:  "交代主要关系的最终状态，形成信息反转",
		Checklist: "用末尾意象回应开场",
	},
	{
		ID:        "blueprint-031",
		Genre:     "mystery",
		Phase:     "opening-image",
		Goal:      "用可视化日常建立主人公当前秩序，突出线索拼合",
		Conflict:  "展示尚未解决的核心缺口，形成真相代价",
		Checklist: "让环境细节暗示主题",
	},
	{
		ID:        "blueprint-032",
		Genre:     "mystery",
		Phase:     "inciting-event",
		Goal:      "用不可逆事件打破原有平衡，突出线索拼合",
		Conflict:  "迫使主人公回应外部变化，形成真相代价",
		Checklist: "确保事件与核心欲望相关",
	},
	{
		ID:        "blueprint-033",
		Genre:     "mystery",
		Phase:     "debate",
		Goal:      "让主人公比较行动与逃避的代价，突出线索拼合",
		Conflict:  "通过关系冲突暴露恐惧，形成真相代价",
		Checklist: "建立进入新局面的必要性",
	},
	{
		ID:        "blueprint-034",
		Genre:     "mystery",
		Phase:     "threshold",
		Goal:      "让主人公做出明确且可见的选择，突出线索拼合",
		Conflict:  "改变地点关系或行动规则，形成真相代价",
		Checklist: "给予选择即时后果",
	},
	{
		ID:        "blueprint-035",
		Genre:     "mystery",
		Phase:     "progress",
		Goal:      "用连续行动检验主人公的方法，突出线索拼合",
		Conflict:  "同步推进目标与关系压力，形成真相代价",
		Checklist: "让每次得失改变下一步",
	},
	{
		ID:        "blueprint-036",
		Genre:     "mystery",
		Phase:     "midpoint",
		Goal:      "制造改变目标理解的重大结果，突出线索拼合",
		Conflict:  "提升公开风险或私人风险，形成真相代价",
		Checklist: "把主题问题转化为行动",
	},
	{
		ID:        "blueprint-037",
		Genre:     "mystery",
		Phase:     "pressure",
		Goal:      "让对手与内在缺陷同时收紧，突出线索拼合",
		Conflict:  "减少可用资源与退路，形成真相代价",
		Checklist: "迫使关系承担剧情功能",
	},
	{
		ID:        "blueprint-038",
		Genre:     "mystery",
		Phase:     "crisis",
		Goal:      "让旧方法彻底失效并暴露代价，突出线索拼合",
		Conflict:  "要求主人公承认真实需求，形成真相代价",
		Checklist: "把最终选择准备充分",
	},
	{
		ID:        "blueprint-039",
		Genre:     "mystery",
		Phase:     "climax",
		Goal:      "用主动选择解决核心对抗，突出线索拼合",
		Conflict:  "让能力成长体现在行动中，形成真相代价",
		Checklist: "回收关键伏笔与关系承诺",
	},
	{
		ID:        "blueprint-040",
		Genre:     "mystery",
		Phase:     "resolution",
		Goal:      "展示新秩序及其具体差异，突出线索拼合",
		Conflict:  "交代主要关系的最终状态，形成真相代价",
		Checklist: "用末尾意象回应开场",
	},
	{
		ID:        "blueprint-041",
		Genre:     "romance",
		Phase:     "opening-image",
		Goal:      "用可视化日常建立主人公当前秩序，突出亲密建立",
		Conflict:  "展示尚未解决的核心缺口，形成脆弱表达",
		Checklist: "让环境细节暗示主题",
	},
	{
		ID:        "blueprint-042",
		Genre:     "romance",
		Phase:     "inciting-event",
		Goal:      "用不可逆事件打破原有平衡，突出亲密建立",
		Conflict:  "迫使主人公回应外部变化，形成脆弱表达",
		Checklist: "确保事件与核心欲望相关",
	},
	{
		ID:        "blueprint-043",
		Genre:     "romance",
		Phase:     "debate",
		Goal:      "让主人公比较行动与逃避的代价，突出亲密建立",
		Conflict:  "通过关系冲突暴露恐惧，形成脆弱表达",
		Checklist: "建立进入新局面的必要性",
	},
	{
		ID:        "blueprint-044",
		Genre:     "romance",
		Phase:     "threshold",
		Goal:      "让主人公做出明确且可见的选择，突出亲密建立",
		Conflict:  "改变地点关系或行动规则，形成脆弱表达",
		Checklist: "给予选择即时后果",
	},
	{
		ID:        "blueprint-045",
		Genre:     "romance",
		Phase:     "progress",
		Goal:      "用连续行动检验主人公的方法，突出亲密建立",
		Conflict:  "同步推进目标与关系压力，形成脆弱表达",
		Checklist: "让每次得失改变下一步",
	},
	{
		ID:        "blueprint-046",
		Genre:     "romance",
		Phase:     "midpoint",
		Goal:      "制造改变目标理解的重大结果，突出亲密建立",
		Conflict:  "提升公开风险或私人风险，形成脆弱表达",
		Checklist: "把主题问题转化为行动",
	},
	{
		ID:        "blueprint-047",
		Genre:     "romance",
		Phase:     "pressure",
		Goal:      "让对手与内在缺陷同时收紧，突出亲密建立",
		Conflict:  "减少可用资源与退路，形成脆弱表达",
		Checklist: "迫使关系承担剧情功能",
	},
	{
		ID:        "blueprint-048",
		Genre:     "romance",
		Phase:     "crisis",
		Goal:      "让旧方法彻底失效并暴露代价，突出亲密建立",
		Conflict:  "要求主人公承认真实需求，形成脆弱表达",
		Checklist: "把最终选择准备充分",
	},
	{
		ID:        "blueprint-049",
		Genre:     "romance",
		Phase:     "climax",
		Goal:      "用主动选择解决核心对抗，突出亲密建立",
		Conflict:  "让能力成长体现在行动中，形成脆弱表达",
		Checklist: "回收关键伏笔与关系承诺",
	},
	{
		ID:        "blueprint-050",
		Genre:     "romance",
		Phase:     "resolution",
		Goal:      "展示新秩序及其具体差异，突出亲密建立",
		Conflict:  "交代主要关系的最终状态，形成脆弱表达",
		Checklist: "用末尾意象回应开场",
	},
	{
		ID:        "blueprint-051",
		Genre:     "adventure",
		Phase:     "opening-image",
		Goal:      "用可视化日常建立主人公当前秩序，突出未知探索",
		Conflict:  "展示尚未解决的核心缺口，形成团队信任",
		Checklist: "让环境细节暗示主题",
	},
	{
		ID:        "blueprint-052",
		Genre:     "adventure",
		Phase:     "inciting-event",
		Goal:      "用不可逆事件打破原有平衡，突出未知探索",
		Conflict:  "迫使主人公回应外部变化，形成团队信任",
		Checklist: "确保事件与核心欲望相关",
	},
	{
		ID:        "blueprint-053",
		Genre:     "adventure",
		Phase:     "debate",
		Goal:      "让主人公比较行动与逃避的代价，突出未知探索",
		Conflict:  "通过关系冲突暴露恐惧，形成团队信任",
		Checklist: "建立进入新局面的必要性",
	},
	{
		ID:        "blueprint-054",
		Genre:     "adventure",
		Phase:     "threshold",
		Goal:      "让主人公做出明确且可见的选择，突出未知探索",
		Conflict:  "改变地点关系或行动规则，形成团队信任",
		Checklist: "给予选择即时后果",
	},
	{
		ID:        "blueprint-055",
		Genre:     "adventure",
		Phase:     "progress",
		Goal:      "用连续行动检验主人公的方法，突出未知探索",
		Conflict:  "同步推进目标与关系压力，形成团队信任",
		Checklist: "让每次得失改变下一步",
	},
	{
		ID:        "blueprint-056",
		Genre:     "adventure",
		Phase:     "midpoint",
		Goal:      "制造改变目标理解的重大结果，突出未知探索",
		Conflict:  "提升公开风险或私人风险，形成团队信任",
		Checklist: "把主题问题转化为行动",
	},
	{
		ID:        "blueprint-057",
		Genre:     "adventure",
		Phase:     "pressure",
		Goal:      "让对手与内在缺陷同时收紧，突出未知探索",
		Conflict:  "减少可用资源与退路，形成团队信任",
		Checklist: "迫使关系承担剧情功能",
	},
	{
		ID:        "blueprint-058",
		Genre:     "adventure",
		Phase:     "crisis",
		Goal:      "让旧方法彻底失效并暴露代价，突出未知探索",
		Conflict:  "要求主人公承认真实需求，形成团队信任",
		Checklist: "把最终选择准备充分",
	},
	{
		ID:        "blueprint-059",
		Genre:     "adventure",
		Phase:     "climax",
		Goal:      "用主动选择解决核心对抗，突出未知探索",
		Conflict:  "让能力成长体现在行动中，形成团队信任",
		Checklist: "回收关键伏笔与关系承诺",
	},
	{
		ID:        "blueprint-060",
		Genre:     "adventure",
		Phase:     "resolution",
		Goal:      "展示新秩序及其具体差异，突出未知探索",
		Conflict:  "交代主要关系的最终状态，形成团队信任",
		Checklist: "用末尾意象回应开场",
	},
	{
		ID:        "blueprint-061",
		Genre:     "fantasy",
		Phase:     "opening-image",
		Goal:      "用可视化日常建立主人公当前秩序，突出规则奇观",
		Conflict:  "展示尚未解决的核心缺口，形成权力责任",
		Checklist: "让环境细节暗示主题",
	},
	{
		ID:        "blueprint-062",
		Genre:     "fantasy",
		Phase:     "inciting-event",
		Goal:      "用不可逆事件打破原有平衡，突出规则奇观",
		Conflict:  "迫使主人公回应外部变化，形成权力责任",
		Checklist: "确保事件与核心欲望相关",
	},
	{
		ID:        "blueprint-063",
		Genre:     "fantasy",
		Phase:     "debate",
		Goal:      "让主人公比较行动与逃避的代价，突出规则奇观",
		Conflict:  "通过关系冲突暴露恐惧，形成权力责任",
		Checklist: "建立进入新局面的必要性",
	},
	{
		ID:        "blueprint-064",
		Genre:     "fantasy",
		Phase:     "threshold",
		Goal:      "让主人公做出明确且可见的选择，突出规则奇观",
		Conflict:  "改变地点关系或行动规则，形成权力责任",
		Checklist: "给予选择即时后果",
	},
	{
		ID:        "blueprint-065",
		Genre:     "fantasy",
		Phase:     "progress",
		Goal:      "用连续行动检验主人公的方法，突出规则奇观",
		Conflict:  "同步推进目标与关系压力，形成权力责任",
		Checklist: "让每次得失改变下一步",
	},
	{
		ID:        "blueprint-066",
		Genre:     "fantasy",
		Phase:     "midpoint",
		Goal:      "制造改变目标理解的重大结果，突出规则奇观",
		Conflict:  "提升公开风险或私人风险，形成权力责任",
		Checklist: "把主题问题转化为行动",
	},
	{
		ID:        "blueprint-067",
		Genre:     "fantasy",
		Phase:     "pressure",
		Goal:      "让对手与内在缺陷同时收紧，突出规则奇观",
		Conflict:  "减少可用资源与退路，形成权力责任",
		Checklist: "迫使关系承担剧情功能",
	},
	{
		ID:        "blueprint-068",
		Genre:     "fantasy",
		Phase:     "crisis",
		Goal:      "让旧方法彻底失效并暴露代价，突出规则奇观",
		Conflict:  "要求主人公承认真实需求，形成权力责任",
		Checklist: "把最终选择准备充分",
	},
	{
		ID:        "blueprint-069",
		Genre:     "fantasy",
		Phase:     "climax",
		Goal:      "用主动选择解决核心对抗，突出规则奇观",
		Conflict:  "让能力成长体现在行动中，形成权力责任",
		Checklist: "回收关键伏笔与关系承诺",
	},
	{
		ID:        "blueprint-070",
		Genre:     "fantasy",
		Phase:     "resolution",
		Goal:      "展示新秩序及其具体差异，突出规则奇观",
		Conflict:  "交代主要关系的最终状态，形成权力责任",
		Checklist: "用末尾意象回应开场",
	},
	{
		ID:        "blueprint-071",
		Genre:     "science-fiction",
		Phase:     "opening-image",
		Goal:      "用可视化日常建立主人公当前秩序，突出技术后果",
		Conflict:  "展示尚未解决的核心缺口，形成人性边界",
		Checklist: "让环境细节暗示主题",
	},
	{
		ID:        "blueprint-072",
		Genre:     "science-fiction",
		Phase:     "inciting-event",
		Goal:      "用不可逆事件打破原有平衡，突出技术后果",
		Conflict:  "迫使主人公回应外部变化，形成人性边界",
		Checklist: "确保事件与核心欲望相关",
	},
	{
		ID:        "blueprint-073",
		Genre:     "science-fiction",
		Phase:     "debate",
		Goal:      "让主人公比较行动与逃避的代价，突出技术后果",
		Conflict:  "通过关系冲突暴露恐惧，形成人性边界",
		Checklist: "建立进入新局面的必要性",
	},
	{
		ID:        "blueprint-074",
		Genre:     "science-fiction",
		Phase:     "threshold",
		Goal:      "让主人公做出明确且可见的选择，突出技术后果",
		Conflict:  "改变地点关系或行动规则，形成人性边界",
		Checklist: "给予选择即时后果",
	},
	{
		ID:        "blueprint-075",
		Genre:     "science-fiction",
		Phase:     "progress",
		Goal:      "用连续行动检验主人公的方法，突出技术后果",
		Conflict:  "同步推进目标与关系压力，形成人性边界",
		Checklist: "让每次得失改变下一步",
	},
	{
		ID:        "blueprint-076",
		Genre:     "science-fiction",
		Phase:     "midpoint",
		Goal:      "制造改变目标理解的重大结果，突出技术后果",
		Conflict:  "提升公开风险或私人风险，形成人性边界",
		Checklist: "把主题问题转化为行动",
	},
	{
		ID:        "blueprint-077",
		Genre:     "science-fiction",
		Phase:     "pressure",
		Goal:      "让对手与内在缺陷同时收紧，突出技术后果",
		Conflict:  "减少可用资源与退路，形成人性边界",
		Checklist: "迫使关系承担剧情功能",
	},
	{
		ID:        "blueprint-078",
		Genre:     "science-fiction",
		Phase:     "crisis",
		Goal:      "让旧方法彻底失效并暴露代价，突出技术后果",
		Conflict:  "要求主人公承认真实需求，形成人性边界",
		Checklist: "把最终选择准备充分",
	},
	{
		ID:        "blueprint-079",
		Genre:     "science-fiction",
		Phase:     "climax",
		Goal:      "用主动选择解决核心对抗，突出技术后果",
		Conflict:  "让能力成长体现在行动中，形成人性边界",
		Checklist: "回收关键伏笔与关系承诺",
	},
	{
		ID:        "blueprint-080",
		Genre:     "science-fiction",
		Phase:     "resolution",
		Goal:      "展示新秩序及其具体差异，突出技术后果",
		Conflict:  "交代主要关系的最终状态，形成人性边界",
		Checklist: "用末尾意象回应开场",
	},
	{
		ID:        "blueprint-081",
		Genre:     "crime",
		Phase:     "opening-image",
		Goal:      "用可视化日常建立主人公当前秩序，突出道德困境",
		Conflict:  "展示尚未解决的核心缺口，形成证据压力",
		Checklist: "让环境细节暗示主题",
	},
	{
		ID:        "blueprint-082",
		Genre:     "crime",
		Phase:     "inciting-event",
		Goal:      "用不可逆事件打破原有平衡，突出道德困境",
		Conflict:  "迫使主人公回应外部变化，形成证据压力",
		Checklist: "确保事件与核心欲望相关",
	},
	{
		ID:        "blueprint-083",
		Genre:     "crime",
		Phase:     "debate",
		Goal:      "让主人公比较行动与逃避的代价，突出道德困境",
		Conflict:  "通过关系冲突暴露恐惧，形成证据压力",
		Checklist: "建立进入新局面的必要性",
	},
	{
		ID:        "blueprint-084",
		Genre:     "crime",
		Phase:     "threshold",
		Goal:      "让主人公做出明确且可见的选择，突出道德困境",
		Conflict:  "改变地点关系或行动规则，形成证据压力",
		Checklist: "给予选择即时后果",
	},
	{
		ID:        "blueprint-085",
		Genre:     "crime",
		Phase:     "progress",
		Goal:      "用连续行动检验主人公的方法，突出道德困境",
		Conflict:  "同步推进目标与关系压力，形成证据压力",
		Checklist: "让每次得失改变下一步",
	},
	{
		ID:        "blueprint-086",
		Genre:     "crime",
		Phase:     "midpoint",
		Goal:      "制造改变目标理解的重大结果，突出道德困境",
		Conflict:  "提升公开风险或私人风险，形成证据压力",
		Checklist: "把主题问题转化为行动",
	},
	{
		ID:        "blueprint-087",
		Genre:     "crime",
		Phase:     "pressure",
		Goal:      "让对手与内在缺陷同时收紧，突出道德困境",
		Conflict:  "减少可用资源与退路，形成证据压力",
		Checklist: "迫使关系承担剧情功能",
	},
	{
		ID:        "blueprint-088",
		Genre:     "crime",
		Phase:     "crisis",
		Goal:      "让旧方法彻底失效并暴露代价，突出道德困境",
		Conflict:  "要求主人公承认真实需求，形成证据压力",
		Checklist: "把最终选择准备充分",
	},
	{
		ID:        "blueprint-089",
		Genre:     "crime",
		Phase:     "climax",
		Goal:      "用主动选择解决核心对抗，突出道德困境",
		Conflict:  "让能力成长体现在行动中，形成证据压力",
		Checklist: "回收关键伏笔与关系承诺",
	},
	{
		ID:        "blueprint-090",
		Genre:     "crime",
		Phase:     "resolution",
		Goal:      "展示新秩序及其具体差异，突出道德困境",
		Conflict:  "交代主要关系的最终状态，形成证据压力",
		Checklist: "用末尾意象回应开场",
	},
	{
		ID:        "blueprint-091",
		Genre:     "family",
		Phase:     "opening-image",
		Goal:      "用可视化日常建立主人公当前秩序，突出代际冲突",
		Conflict:  "展示尚未解决的核心缺口，形成理解和解",
		Checklist: "让环境细节暗示主题",
	},
	{
		ID:        "blueprint-092",
		Genre:     "family",
		Phase:     "inciting-event",
		Goal:      "用不可逆事件打破原有平衡，突出代际冲突",
		Conflict:  "迫使主人公回应外部变化，形成理解和解",
		Checklist: "确保事件与核心欲望相关",
	},
	{
		ID:        "blueprint-093",
		Genre:     "family",
		Phase:     "debate",
		Goal:      "让主人公比较行动与逃避的代价，突出代际冲突",
		Conflict:  "通过关系冲突暴露恐惧，形成理解和解",
		Checklist: "建立进入新局面的必要性",
	},
	{
		ID:        "blueprint-094",
		Genre:     "family",
		Phase:     "threshold",
		Goal:      "让主人公做出明确且可见的选择，突出代际冲突",
		Conflict:  "改变地点关系或行动规则，形成理解和解",
		Checklist: "给予选择即时后果",
	},
	{
		ID:        "blueprint-095",
		Genre:     "family",
		Phase:     "progress",
		Goal:      "用连续行动检验主人公的方法，突出代际冲突",
		Conflict:  "同步推进目标与关系压力，形成理解和解",
		Checklist: "让每次得失改变下一步",
	},
	{
		ID:        "blueprint-096",
		Genre:     "family",
		Phase:     "midpoint",
		Goal:      "制造改变目标理解的重大结果，突出代际冲突",
		Conflict:  "提升公开风险或私人风险，形成理解和解",
		Checklist: "把主题问题转化为行动",
	},
	{
		ID:        "blueprint-097",
		Genre:     "family",
		Phase:     "pressure",
		Goal:      "让对手与内在缺陷同时收紧，突出代际冲突",
		Conflict:  "减少可用资源与退路，形成理解和解",
		Checklist: "迫使关系承担剧情功能",
	},
	{
		ID:        "blueprint-098",
		Genre:     "family",
		Phase:     "crisis",
		Goal:      "让旧方法彻底失效并暴露代价，突出代际冲突",
		Conflict:  "要求主人公承认真实需求，形成理解和解",
		Checklist: "把最终选择准备充分",
	},
	{
		ID:        "blueprint-099",
		Genre:     "family",
		Phase:     "climax",
		Goal:      "用主动选择解决核心对抗，突出代际冲突",
		Conflict:  "让能力成长体现在行动中，形成理解和解",
		Checklist: "回收关键伏笔与关系承诺",
	},
	{
		ID:        "blueprint-100",
		Genre:     "family",
		Phase:     "resolution",
		Goal:      "展示新秩序及其具体差异，突出代际冲突",
		Conflict:  "交代主要关系的最终状态，形成理解和解",
		Checklist: "用末尾意象回应开场",
	},
	{
		ID:        "blueprint-101",
		Genre:     "historical",
		Phase:     "opening-image",
		Goal:      "用可视化日常建立主人公当前秩序，突出时代限制",
		Conflict:  "展示尚未解决的核心缺口，形成个人选择",
		Checklist: "让环境细节暗示主题",
	},
	{
		ID:        "blueprint-102",
		Genre:     "historical",
		Phase:     "inciting-event",
		Goal:      "用不可逆事件打破原有平衡，突出时代限制",
		Conflict:  "迫使主人公回应外部变化，形成个人选择",
		Checklist: "确保事件与核心欲望相关",
	},
	{
		ID:        "blueprint-103",
		Genre:     "historical",
		Phase:     "debate",
		Goal:      "让主人公比较行动与逃避的代价，突出时代限制",
		Conflict:  "通过关系冲突暴露恐惧，形成个人选择",
		Checklist: "建立进入新局面的必要性",
	},
	{
		ID:        "blueprint-104",
		Genre:     "historical",
		Phase:     "threshold",
		Goal:      "让主人公做出明确且可见的选择，突出时代限制",
		Conflict:  "改变地点关系或行动规则，形成个人选择",
		Checklist: "给予选择即时后果",
	},
	{
		ID:        "blueprint-105",
		Genre:     "historical",
		Phase:     "progress",
		Goal:      "用连续行动检验主人公的方法，突出时代限制",
		Conflict:  "同步推进目标与关系压力，形成个人选择",
		Checklist: "让每次得失改变下一步",
	},
	{
		ID:        "blueprint-106",
		Genre:     "historical",
		Phase:     "midpoint",
		Goal:      "制造改变目标理解的重大结果，突出时代限制",
		Conflict:  "提升公开风险或私人风险，形成个人选择",
		Checklist: "把主题问题转化为行动",
	},
	{
		ID:        "blueprint-107",
		Genre:     "historical",
		Phase:     "pressure",
		Goal:      "让对手与内在缺陷同时收紧，突出时代限制",
		Conflict:  "减少可用资源与退路，形成个人选择",
		Checklist: "迫使关系承担剧情功能",
	},
	{
		ID:        "blueprint-108",
		Genre:     "historical",
		Phase:     "crisis",
		Goal:      "让旧方法彻底失效并暴露代价，突出时代限制",
		Conflict:  "要求主人公承认真实需求，形成个人选择",
		Checklist: "把最终选择准备充分",
	},
	{
		ID:        "blueprint-109",
		Genre:     "historical",
		Phase:     "climax",
		Goal:      "用主动选择解决核心对抗，突出时代限制",
		Conflict:  "让能力成长体现在行动中，形成个人选择",
		Checklist: "回收关键伏笔与关系承诺",
	},
	{
		ID:        "blueprint-110",
		Genre:     "historical",
		Phase:     "resolution",
		Goal:      "展示新秩序及其具体差异，突出时代限制",
		Conflict:  "交代主要关系的最终状态，形成个人选择",
		Checklist: "用末尾意象回应开场",
	},
	{
		ID:        "blueprint-111",
		Genre:     "war",
		Phase:     "opening-image",
		Goal:      "用可视化日常建立主人公当前秩序，突出生存压力",
		Conflict:  "展示尚未解决的核心缺口，形成共同责任",
		Checklist: "让环境细节暗示主题",
	},
	{
		ID:        "blueprint-112",
		Genre:     "war",
		Phase:     "inciting-event",
		Goal:      "用不可逆事件打破原有平衡，突出生存压力",
		Conflict:  "迫使主人公回应外部变化，形成共同责任",
		Checklist: "确保事件与核心欲望相关",
	},
	{
		ID:        "blueprint-113",
		Genre:     "war",
		Phase:     "debate",
		Goal:      "让主人公比较行动与逃避的代价，突出生存压力",
		Conflict:  "通过关系冲突暴露恐惧，形成共同责任",
		Checklist: "建立进入新局面的必要性",
	},
	{
		ID:        "blueprint-114",
		Genre:     "war",
		Phase:     "threshold",
		Goal:      "让主人公做出明确且可见的选择，突出生存压力",
		Conflict:  "改变地点关系或行动规则，形成共同责任",
		Checklist: "给予选择即时后果",
	},
	{
		ID:        "blueprint-115",
		Genre:     "war",
		Phase:     "progress",
		Goal:      "用连续行动检验主人公的方法，突出生存压力",
		Conflict:  "同步推进目标与关系压力，形成共同责任",
		Checklist: "让每次得失改变下一步",
	},
	{
		ID:        "blueprint-116",
		Genre:     "war",
		Phase:     "midpoint",
		Goal:      "制造改变目标理解的重大结果，突出生存压力",
		Conflict:  "提升公开风险或私人风险，形成共同责任",
		Checklist: "把主题问题转化为行动",
	},
	{
		ID:        "blueprint-117",
		Genre:     "war",
		Phase:     "pressure",
		Goal:      "让对手与内在缺陷同时收紧，突出生存压力",
		Conflict:  "减少可用资源与退路，形成共同责任",
		Checklist: "迫使关系承担剧情功能",
	},
	{
		ID:        "blueprint-118",
		Genre:     "war",
		Phase:     "crisis",
		Goal:      "让旧方法彻底失效并暴露代价，突出生存压力",
		Conflict:  "要求主人公承认真实需求，形成共同责任",
		Checklist: "把最终选择准备充分",
	},
	{
		ID:        "blueprint-119",
		Genre:     "war",
		Phase:     "climax",
		Goal:      "用主动选择解决核心对抗，突出生存压力",
		Conflict:  "让能力成长体现在行动中，形成共同责任",
		Checklist: "回收关键伏笔与关系承诺",
	},
	{
		ID:        "blueprint-120",
		Genre:     "war",
		Phase:     "resolution",
		Goal:      "展示新秩序及其具体差异，突出生存压力",
		Conflict:  "交代主要关系的最终状态，形成共同责任",
		Checklist: "用末尾意象回应开场",
	},
	{
		ID:        "blueprint-121",
		Genre:     "sports",
		Phase:     "opening-image",
		Goal:      "用可视化日常建立主人公当前秩序，突出竞技目标",
		Conflict:  "展示尚未解决的核心缺口，形成团队成长",
		Checklist: "让环境细节暗示主题",
	},
	{
		ID:        "blueprint-122",
		Genre:     "sports",
		Phase:     "inciting-event",
		Goal:      "用不可逆事件打破原有平衡，突出竞技目标",
		Conflict:  "迫使主人公回应外部变化，形成团队成长",
		Checklist: "确保事件与核心欲望相关",
	},
	{
		ID:        "blueprint-123",
		Genre:     "sports",
		Phase:     "debate",
		Goal:      "让主人公比较行动与逃避的代价，突出竞技目标",
		Conflict:  "通过关系冲突暴露恐惧，形成团队成长",
		Checklist: "建立进入新局面的必要性",
	},
	{
		ID:        "blueprint-124",
		Genre:     "sports",
		Phase:     "threshold",
		Goal:      "让主人公做出明确且可见的选择，突出竞技目标",
		Conflict:  "改变地点关系或行动规则，形成团队成长",
		Checklist: "给予选择即时后果",
	},
	{
		ID:        "blueprint-125",
		Genre:     "sports",
		Phase:     "progress",
		Goal:      "用连续行动检验主人公的方法，突出竞技目标",
		Conflict:  "同步推进目标与关系压力，形成团队成长",
		Checklist: "让每次得失改变下一步",
	},
	{
		ID:        "blueprint-126",
		Genre:     "sports",
		Phase:     "midpoint",
		Goal:      "制造改变目标理解的重大结果，突出竞技目标",
		Conflict:  "提升公开风险或私人风险，形成团队成长",
		Checklist: "把主题问题转化为行动",
	},
	{
		ID:        "blueprint-127",
		Genre:     "sports",
		Phase:     "pressure",
		Goal:      "让对手与内在缺陷同时收紧，突出竞技目标",
		Conflict:  "减少可用资源与退路，形成团队成长",
		Checklist: "迫使关系承担剧情功能",
	},
	{
		ID:        "blueprint-128",
		Genre:     "sports",
		Phase:     "crisis",
		Goal:      "让旧方法彻底失效并暴露代价，突出竞技目标",
		Conflict:  "要求主人公承认真实需求，形成团队成长",
		Checklist: "把最终选择准备充分",
	},
	{
		ID:        "blueprint-129",
		Genre:     "sports",
		Phase:     "climax",
		Goal:      "用主动选择解决核心对抗，突出竞技目标",
		Conflict:  "让能力成长体现在行动中，形成团队成长",
		Checklist: "回收关键伏笔与关系承诺",
	},
	{
		ID:        "blueprint-130",
		Genre:     "sports",
		Phase:     "resolution",
		Goal:      "展示新秩序及其具体差异，突出竞技目标",
		Conflict:  "交代主要关系的最终状态，形成团队成长",
		Checklist: "用末尾意象回应开场",
	},
	{
		ID:        "blueprint-131",
		Genre:     "musical",
		Phase:     "opening-image",
		Goal:      "用可视化日常建立主人公当前秩序，突出情绪外化",
		Conflict:  "展示尚未解决的核心缺口，形成主题回响",
		Checklist: "让环境细节暗示主题",
	},
	{
		ID:        "blueprint-132",
		Genre:     "musical",
		Phase:     "inciting-event",
		Goal:      "用不可逆事件打破原有平衡，突出情绪外化",
		Conflict:  "迫使主人公回应外部变化，形成主题回响",
		Checklist: "确保事件与核心欲望相关",
	},
	{
		ID:        "blueprint-133",
		Genre:     "musical",
		Phase:     "debate",
		Goal:      "让主人公比较行动与逃避的代价，突出情绪外化",
		Conflict:  "通过关系冲突暴露恐惧，形成主题回响",
		Checklist: "建立进入新局面的必要性",
	},
	{
		ID:        "blueprint-134",
		Genre:     "musical",
		Phase:     "threshold",
		Goal:      "让主人公做出明确且可见的选择，突出情绪外化",
		Conflict:  "改变地点关系或行动规则，形成主题回响",
		Checklist: "给予选择即时后果",
	},
	{
		ID:        "blueprint-135",
		Genre:     "musical",
		Phase:     "progress",
		Goal:      "用连续行动检验主人公的方法，突出情绪外化",
		Conflict:  "同步推进目标与关系压力，形成主题回响",
		Checklist: "让每次得失改变下一步",
	},
	{
		ID:        "blueprint-136",
		Genre:     "musical",
		Phase:     "midpoint",
		Goal:      "制造改变目标理解的重大结果，突出情绪外化",
		Conflict:  "提升公开风险或私人风险，形成主题回响",
		Checklist: "把主题问题转化为行动",
	},
	{
		ID:        "blueprint-137",
		Genre:     "musical",
		Phase:     "pressure",
		Goal:      "让对手与内在缺陷同时收紧，突出情绪外化",
		Conflict:  "减少可用资源与退路，形成主题回响",
		Checklist: "迫使关系承担剧情功能",
	},
	{
		ID:        "blueprint-138",
		Genre:     "musical",
		Phase:     "crisis",
		Goal:      "让旧方法彻底失效并暴露代价，突出情绪外化",
		Conflict:  "要求主人公承认真实需求，形成主题回响",
		Checklist: "把最终选择准备充分",
	},
	{
		ID:        "blueprint-139",
		Genre:     "musical",
		Phase:     "climax",
		Goal:      "用主动选择解决核心对抗，突出情绪外化",
		Conflict:  "让能力成长体现在行动中，形成主题回响",
		Checklist: "回收关键伏笔与关系承诺",
	},
	{
		ID:        "blueprint-140",
		Genre:     "musical",
		Phase:     "resolution",
		Goal:      "展示新秩序及其具体差异，突出情绪外化",
		Conflict:  "交代主要关系的最终状态，形成主题回响",
		Checklist: "用末尾意象回应开场",
	},
	{
		ID:        "blueprint-141",
		Genre:     "western",
		Phase:     "opening-image",
		Goal:      "用可视化日常建立主人公当前秩序，突出边疆秩序",
		Conflict:  "展示尚未解决的核心缺口，形成正义代价",
		Checklist: "让环境细节暗示主题",
	},
	{
		ID:        "blueprint-142",
		Genre:     "western",
		Phase:     "inciting-event",
		Goal:      "用不可逆事件打破原有平衡，突出边疆秩序",
		Conflict:  "迫使主人公回应外部变化，形成正义代价",
		Checklist: "确保事件与核心欲望相关",
	},
	{
		ID:        "blueprint-143",
		Genre:     "western",
		Phase:     "debate",
		Goal:      "让主人公比较行动与逃避的代价，突出边疆秩序",
		Conflict:  "通过关系冲突暴露恐惧，形成正义代价",
		Checklist: "建立进入新局面的必要性",
	},
	{
		ID:        "blueprint-144",
		Genre:     "western",
		Phase:     "threshold",
		Goal:      "让主人公做出明确且可见的选择，突出边疆秩序",
		Conflict:  "改变地点关系或行动规则，形成正义代价",
		Checklist: "给予选择即时后果",
	},
	{
		ID:        "blueprint-145",
		Genre:     "western",
		Phase:     "progress",
		Goal:      "用连续行动检验主人公的方法，突出边疆秩序",
		Conflict:  "同步推进目标与关系压力，形成正义代价",
		Checklist: "让每次得失改变下一步",
	},
	{
		ID:        "blueprint-146",
		Genre:     "western",
		Phase:     "midpoint",
		Goal:      "制造改变目标理解的重大结果，突出边疆秩序",
		Conflict:  "提升公开风险或私人风险，形成正义代价",
		Checklist: "把主题问题转化为行动",
	},
	{
		ID:        "blueprint-147",
		Genre:     "western",
		Phase:     "pressure",
		Goal:      "让对手与内在缺陷同时收紧，突出边疆秩序",
		Conflict:  "减少可用资源与退路，形成正义代价",
		Checklist: "迫使关系承担剧情功能",
	},
	{
		ID:        "blueprint-148",
		Genre:     "western",
		Phase:     "crisis",
		Goal:      "让旧方法彻底失效并暴露代价，突出边疆秩序",
		Conflict:  "要求主人公承认真实需求，形成正义代价",
		Checklist: "把最终选择准备充分",
	},
	{
		ID:        "blueprint-149",
		Genre:     "western",
		Phase:     "climax",
		Goal:      "用主动选择解决核心对抗，突出边疆秩序",
		Conflict:  "让能力成长体现在行动中，形成正义代价",
		Checklist: "回收关键伏笔与关系承诺",
	},
	{
		ID:        "blueprint-150",
		Genre:     "western",
		Phase:     "resolution",
		Goal:      "展示新秩序及其具体差异，突出边疆秩序",
		Conflict:  "交代主要关系的最终状态，形成正义代价",
		Checklist: "用末尾意象回应开场",
	},
	{
		ID:        "blueprint-151",
		Genre:     "noir",
		Phase:     "opening-image",
		Goal:      "用可视化日常建立主人公当前秩序，突出欲望迷局",
		Conflict:  "展示尚未解决的核心缺口，形成自我审判",
		Checklist: "让环境细节暗示主题",
	},
	{
		ID:        "blueprint-152",
		Genre:     "noir",
		Phase:     "inciting-event",
		Goal:      "用不可逆事件打破原有平衡，突出欲望迷局",
		Conflict:  "迫使主人公回应外部变化，形成自我审判",
		Checklist: "确保事件与核心欲望相关",
	},
	{
		ID:        "blueprint-153",
		Genre:     "noir",
		Phase:     "debate",
		Goal:      "让主人公比较行动与逃避的代价，突出欲望迷局",
		Conflict:  "通过关系冲突暴露恐惧，形成自我审判",
		Checklist: "建立进入新局面的必要性",
	},
	{
		ID:        "blueprint-154",
		Genre:     "noir",
		Phase:     "threshold",
		Goal:      "让主人公做出明确且可见的选择，突出欲望迷局",
		Conflict:  "改变地点关系或行动规则，形成自我审判",
		Checklist: "给予选择即时后果",
	},
	{
		ID:        "blueprint-155",
		Genre:     "noir",
		Phase:     "progress",
		Goal:      "用连续行动检验主人公的方法，突出欲望迷局",
		Conflict:  "同步推进目标与关系压力，形成自我审判",
		Checklist: "让每次得失改变下一步",
	},
	{
		ID:        "blueprint-156",
		Genre:     "noir",
		Phase:     "midpoint",
		Goal:      "制造改变目标理解的重大结果，突出欲望迷局",
		Conflict:  "提升公开风险或私人风险，形成自我审判",
		Checklist: "把主题问题转化为行动",
	},
	{
		ID:        "blueprint-157",
		Genre:     "noir",
		Phase:     "pressure",
		Goal:      "让对手与内在缺陷同时收紧，突出欲望迷局",
		Conflict:  "减少可用资源与退路，形成自我审判",
		Checklist: "迫使关系承担剧情功能",
	},
	{
		ID:        "blueprint-158",
		Genre:     "noir",
		Phase:     "crisis",
		Goal:      "让旧方法彻底失效并暴露代价，突出欲望迷局",
		Conflict:  "要求主人公承认真实需求，形成自我审判",
		Checklist: "把最终选择准备充分",
	},
	{
		ID:        "blueprint-159",
		Genre:     "noir",
		Phase:     "climax",
		Goal:      "用主动选择解决核心对抗，突出欲望迷局",
		Conflict:  "让能力成长体现在行动中，形成自我审判",
		Checklist: "回收关键伏笔与关系承诺",
	},
	{
		ID:        "blueprint-160",
		Genre:     "noir",
		Phase:     "resolution",
		Goal:      "展示新秩序及其具体差异，突出欲望迷局",
		Conflict:  "交代主要关系的最终状态，形成自我审判",
		Checklist: "用末尾意象回应开场",
	},
	{
		ID:        "blueprint-161",
		Genre:     "satire",
		Phase:     "opening-image",
		Goal:      "用可视化日常建立主人公当前秩序，突出制度荒诞",
		Conflict:  "展示尚未解决的核心缺口，形成价值揭示",
		Checklist: "让环境细节暗示主题",
	},
	{
		ID:        "blueprint-162",
		Genre:     "satire",
		Phase:     "inciting-event",
		Goal:      "用不可逆事件打破原有平衡，突出制度荒诞",
		Conflict:  "迫使主人公回应外部变化，形成价值揭示",
		Checklist: "确保事件与核心欲望相关",
	},
	{
		ID:        "blueprint-163",
		Genre:     "satire",
		Phase:     "debate",
		Goal:      "让主人公比较行动与逃避的代价，突出制度荒诞",
		Conflict:  "通过关系冲突暴露恐惧，形成价值揭示",
		Checklist: "建立进入新局面的必要性",
	},
	{
		ID:        "blueprint-164",
		Genre:     "satire",
		Phase:     "threshold",
		Goal:      "让主人公做出明确且可见的选择，突出制度荒诞",
		Conflict:  "改变地点关系或行动规则，形成价值揭示",
		Checklist: "给予选择即时后果",
	},
	{
		ID:        "blueprint-165",
		Genre:     "satire",
		Phase:     "progress",
		Goal:      "用连续行动检验主人公的方法，突出制度荒诞",
		Conflict:  "同步推进目标与关系压力，形成价值揭示",
		Checklist: "让每次得失改变下一步",
	},
	{
		ID:        "blueprint-166",
		Genre:     "satire",
		Phase:     "midpoint",
		Goal:      "制造改变目标理解的重大结果，突出制度荒诞",
		Conflict:  "提升公开风险或私人风险，形成价值揭示",
		Checklist: "把主题问题转化为行动",
	},
	{
		ID:        "blueprint-167",
		Genre:     "satire",
		Phase:     "pressure",
		Goal:      "让对手与内在缺陷同时收紧，突出制度荒诞",
		Conflict:  "减少可用资源与退路，形成价值揭示",
		Checklist: "迫使关系承担剧情功能",
	},
	{
		ID:        "blueprint-168",
		Genre:     "satire",
		Phase:     "crisis",
		Goal:      "让旧方法彻底失效并暴露代价，突出制度荒诞",
		Conflict:  "要求主人公承认真实需求，形成价值揭示",
		Checklist: "把最终选择准备充分",
	},
	{
		ID:        "blueprint-169",
		Genre:     "satire",
		Phase:     "climax",
		Goal:      "用主动选择解决核心对抗，突出制度荒诞",
		Conflict:  "让能力成长体现在行动中，形成价值揭示",
		Checklist: "回收关键伏笔与关系承诺",
	},
	{
		ID:        "blueprint-170",
		Genre:     "satire",
		Phase:     "resolution",
		Goal:      "展示新秩序及其具体差异，突出制度荒诞",
		Conflict:  "交代主要关系的最终状态，形成价值揭示",
		Checklist: "用末尾意象回应开场",
	},
	{
		ID:        "blueprint-171",
		Genre:     "coming-of-age",
		Phase:     "opening-image",
		Goal:      "用可视化日常建立主人公当前秩序，突出身份探索",
		Conflict:  "展示尚未解决的核心缺口，形成成熟选择",
		Checklist: "让环境细节暗示主题",
	},
	{
		ID:        "blueprint-172",
		Genre:     "coming-of-age",
		Phase:     "inciting-event",
		Goal:      "用不可逆事件打破原有平衡，突出身份探索",
		Conflict:  "迫使主人公回应外部变化，形成成熟选择",
		Checklist: "确保事件与核心欲望相关",
	},
	{
		ID:        "blueprint-173",
		Genre:     "coming-of-age",
		Phase:     "debate",
		Goal:      "让主人公比较行动与逃避的代价，突出身份探索",
		Conflict:  "通过关系冲突暴露恐惧，形成成熟选择",
		Checklist: "建立进入新局面的必要性",
	},
	{
		ID:        "blueprint-174",
		Genre:     "coming-of-age",
		Phase:     "threshold",
		Goal:      "让主人公做出明确且可见的选择，突出身份探索",
		Conflict:  "改变地点关系或行动规则，形成成熟选择",
		Checklist: "给予选择即时后果",
	},
	{
		ID:        "blueprint-175",
		Genre:     "coming-of-age",
		Phase:     "progress",
		Goal:      "用连续行动检验主人公的方法，突出身份探索",
		Conflict:  "同步推进目标与关系压力，形成成熟选择",
		Checklist: "让每次得失改变下一步",
	},
	{
		ID:        "blueprint-176",
		Genre:     "coming-of-age",
		Phase:     "midpoint",
		Goal:      "制造改变目标理解的重大结果，突出身份探索",
		Conflict:  "提升公开风险或私人风险，形成成熟选择",
		Checklist: "把主题问题转化为行动",
	},
	{
		ID:        "blueprint-177",
		Genre:     "coming-of-age",
		Phase:     "pressure",
		Goal:      "让对手与内在缺陷同时收紧，突出身份探索",
		Conflict:  "减少可用资源与退路，形成成熟选择",
		Checklist: "迫使关系承担剧情功能",
	},
	{
		ID:        "blueprint-178",
		Genre:     "coming-of-age",
		Phase:     "crisis",
		Goal:      "让旧方法彻底失效并暴露代价，突出身份探索",
		Conflict:  "要求主人公承认真实需求，形成成熟选择",
		Checklist: "把最终选择准备充分",
	},
	{
		ID:        "blueprint-179",
		Genre:     "coming-of-age",
		Phase:     "climax",
		Goal:      "用主动选择解决核心对抗，突出身份探索",
		Conflict:  "让能力成长体现在行动中，形成成熟选择",
		Checklist: "回收关键伏笔与关系承诺",
	},
	{
		ID:        "blueprint-180",
		Genre:     "coming-of-age",
		Phase:     "resolution",
		Goal:      "展示新秩序及其具体差异，突出身份探索",
		Conflict:  "交代主要关系的最终状态，形成成熟选择",
		Checklist: "用末尾意象回应开场",
	},
	{
		ID:        "blueprint-181",
		Genre:     "road-movie",
		Phase:     "opening-image",
		Goal:      "用可视化日常建立主人公当前秩序，突出旅程变化",
		Conflict:  "展示尚未解决的核心缺口，形成关系重构",
		Checklist: "让环境细节暗示主题",
	},
	{
		ID:        "blueprint-182",
		Genre:     "road-movie",
		Phase:     "inciting-event",
		Goal:      "用不可逆事件打破原有平衡，突出旅程变化",
		Conflict:  "迫使主人公回应外部变化，形成关系重构",
		Checklist: "确保事件与核心欲望相关",
	},
	{
		ID:        "blueprint-183",
		Genre:     "road-movie",
		Phase:     "debate",
		Goal:      "让主人公比较行动与逃避的代价，突出旅程变化",
		Conflict:  "通过关系冲突暴露恐惧，形成关系重构",
		Checklist: "建立进入新局面的必要性",
	},
	{
		ID:        "blueprint-184",
		Genre:     "road-movie",
		Phase:     "threshold",
		Goal:      "让主人公做出明确且可见的选择，突出旅程变化",
		Conflict:  "改变地点关系或行动规则，形成关系重构",
		Checklist: "给予选择即时后果",
	},
	{
		ID:        "blueprint-185",
		Genre:     "road-movie",
		Phase:     "progress",
		Goal:      "用连续行动检验主人公的方法，突出旅程变化",
		Conflict:  "同步推进目标与关系压力，形成关系重构",
		Checklist: "让每次得失改变下一步",
	},
	{
		ID:        "blueprint-186",
		Genre:     "road-movie",
		Phase:     "midpoint",
		Goal:      "制造改变目标理解的重大结果，突出旅程变化",
		Conflict:  "提升公开风险或私人风险，形成关系重构",
		Checklist: "把主题问题转化为行动",
	},
	{
		ID:        "blueprint-187",
		Genre:     "road-movie",
		Phase:     "pressure",
		Goal:      "让对手与内在缺陷同时收紧，突出旅程变化",
		Conflict:  "减少可用资源与退路，形成关系重构",
		Checklist: "迫使关系承担剧情功能",
	},
	{
		ID:        "blueprint-188",
		Genre:     "road-movie",
		Phase:     "crisis",
		Goal:      "让旧方法彻底失效并暴露代价，突出旅程变化",
		Conflict:  "要求主人公承认真实需求，形成关系重构",
		Checklist: "把最终选择准备充分",
	},
	{
		ID:        "blueprint-189",
		Genre:     "road-movie",
		Phase:     "climax",
		Goal:      "用主动选择解决核心对抗，突出旅程变化",
		Conflict:  "让能力成长体现在行动中，形成关系重构",
		Checklist: "回收关键伏笔与关系承诺",
	},
	{
		ID:        "blueprint-190",
		Genre:     "road-movie",
		Phase:     "resolution",
		Goal:      "展示新秩序及其具体差异，突出旅程变化",
		Conflict:  "交代主要关系的最终状态，形成关系重构",
		Checklist: "用末尾意象回应开场",
	},
	{
		ID:        "blueprint-191",
		Genre:     "courtroom",
		Phase:     "opening-image",
		Goal:      "用可视化日常建立主人公当前秩序，突出证词交锋",
		Conflict:  "展示尚未解决的核心缺口，形成伦理判断",
		Checklist: "让环境细节暗示主题",
	},
	{
		ID:        "blueprint-192",
		Genre:     "courtroom",
		Phase:     "inciting-event",
		Goal:      "用不可逆事件打破原有平衡，突出证词交锋",
		Conflict:  "迫使主人公回应外部变化，形成伦理判断",
		Checklist: "确保事件与核心欲望相关",
	},
	{
		ID:        "blueprint-193",
		Genre:     "courtroom",
		Phase:     "debate",
		Goal:      "让主人公比较行动与逃避的代价，突出证词交锋",
		Conflict:  "通过关系冲突暴露恐惧，形成伦理判断",
		Checklist: "建立进入新局面的必要性",
	},
	{
		ID:        "blueprint-194",
		Genre:     "courtroom",
		Phase:     "threshold",
		Goal:      "让主人公做出明确且可见的选择，突出证词交锋",
		Conflict:  "改变地点关系或行动规则，形成伦理判断",
		Checklist: "给予选择即时后果",
	},
	{
		ID:        "blueprint-195",
		Genre:     "courtroom",
		Phase:     "progress",
		Goal:      "用连续行动检验主人公的方法，突出证词交锋",
		Conflict:  "同步推进目标与关系压力，形成伦理判断",
		Checklist: "让每次得失改变下一步",
	},
	{
		ID:        "blueprint-196",
		Genre:     "courtroom",
		Phase:     "midpoint",
		Goal:      "制造改变目标理解的重大结果，突出证词交锋",
		Conflict:  "提升公开风险或私人风险，形成伦理判断",
		Checklist: "把主题问题转化为行动",
	},
	{
		ID:        "blueprint-197",
		Genre:     "courtroom",
		Phase:     "pressure",
		Goal:      "让对手与内在缺陷同时收紧，突出证词交锋",
		Conflict:  "减少可用资源与退路，形成伦理判断",
		Checklist: "迫使关系承担剧情功能",
	},
	{
		ID:        "blueprint-198",
		Genre:     "courtroom",
		Phase:     "crisis",
		Goal:      "让旧方法彻底失效并暴露代价，突出证词交锋",
		Conflict:  "要求主人公承认真实需求，形成伦理判断",
		Checklist: "把最终选择准备充分",
	},
	{
		ID:        "blueprint-199",
		Genre:     "courtroom",
		Phase:     "climax",
		Goal:      "用主动选择解决核心对抗，突出证词交锋",
		Conflict:  "让能力成长体现在行动中，形成伦理判断",
		Checklist: "回收关键伏笔与关系承诺",
	},
	{
		ID:        "blueprint-200",
		Genre:     "courtroom",
		Phase:     "resolution",
		Goal:      "展示新秩序及其具体差异，突出证词交锋",
		Conflict:  "交代主要关系的最终状态，形成伦理判断",
		Checklist: "用末尾意象回应开场",
	},
	{
		ID:        "blueprint-201",
		Genre:     "disaster",
		Phase:     "opening-image",
		Goal:      "用可视化日常建立主人公当前秩序，突出资源危机",
		Conflict:  "展示尚未解决的核心缺口，形成群体协作",
		Checklist: "让环境细节暗示主题",
	},
	{
		ID:        "blueprint-202",
		Genre:     "disaster",
		Phase:     "inciting-event",
		Goal:      "用不可逆事件打破原有平衡，突出资源危机",
		Conflict:  "迫使主人公回应外部变化，形成群体协作",
		Checklist: "确保事件与核心欲望相关",
	},
	{
		ID:        "blueprint-203",
		Genre:     "disaster",
		Phase:     "debate",
		Goal:      "让主人公比较行动与逃避的代价，突出资源危机",
		Conflict:  "通过关系冲突暴露恐惧，形成群体协作",
		Checklist: "建立进入新局面的必要性",
	},
	{
		ID:        "blueprint-204",
		Genre:     "disaster",
		Phase:     "threshold",
		Goal:      "让主人公做出明确且可见的选择，突出资源危机",
		Conflict:  "改变地点关系或行动规则，形成群体协作",
		Checklist: "给予选择即时后果",
	},
	{
		ID:        "blueprint-205",
		Genre:     "disaster",
		Phase:     "progress",
		Goal:      "用连续行动检验主人公的方法，突出资源危机",
		Conflict:  "同步推进目标与关系压力，形成群体协作",
		Checklist: "让每次得失改变下一步",
	},
	{
		ID:        "blueprint-206",
		Genre:     "disaster",
		Phase:     "midpoint",
		Goal:      "制造改变目标理解的重大结果，突出资源危机",
		Conflict:  "提升公开风险或私人风险，形成群体协作",
		Checklist: "把主题问题转化为行动",
	},
	{
		ID:        "blueprint-207",
		Genre:     "disaster",
		Phase:     "pressure",
		Goal:      "让对手与内在缺陷同时收紧，突出资源危机",
		Conflict:  "减少可用资源与退路，形成群体协作",
		Checklist: "迫使关系承担剧情功能",
	},
	{
		ID:        "blueprint-208",
		Genre:     "disaster",
		Phase:     "crisis",
		Goal:      "让旧方法彻底失效并暴露代价，突出资源危机",
		Conflict:  "要求主人公承认真实需求，形成群体协作",
		Checklist: "把最终选择准备充分",
	},
	{
		ID:        "blueprint-209",
		Genre:     "disaster",
		Phase:     "climax",
		Goal:      "用主动选择解决核心对抗，突出资源危机",
		Conflict:  "让能力成长体现在行动中，形成群体协作",
		Checklist: "回收关键伏笔与关系承诺",
	},
	{
		ID:        "blueprint-210",
		Genre:     "disaster",
		Phase:     "resolution",
		Goal:      "展示新秩序及其具体差异，突出资源危机",
		Conflict:  "交代主要关系的最终状态，形成群体协作",
		Checklist: "用末尾意象回应开场",
	},
	{
		ID:        "blueprint-211",
		Genre:     "heist",
		Phase:     "opening-image",
		Goal:      "用可视化日常建立主人公当前秩序，突出计划执行",
		Conflict:  "展示尚未解决的核心缺口，形成忠诚信任",
		Checklist: "让环境细节暗示主题",
	},
	{
		ID:        "blueprint-212",
		Genre:     "heist",
		Phase:     "inciting-event",
		Goal:      "用不可逆事件打破原有平衡，突出计划执行",
		Conflict:  "迫使主人公回应外部变化，形成忠诚信任",
		Checklist: "确保事件与核心欲望相关",
	},
	{
		ID:        "blueprint-213",
		Genre:     "heist",
		Phase:     "debate",
		Goal:      "让主人公比较行动与逃避的代价，突出计划执行",
		Conflict:  "通过关系冲突暴露恐惧，形成忠诚信任",
		Checklist: "建立进入新局面的必要性",
	},
	{
		ID:        "blueprint-214",
		Genre:     "heist",
		Phase:     "threshold",
		Goal:      "让主人公做出明确且可见的选择，突出计划执行",
		Conflict:  "改变地点关系或行动规则，形成忠诚信任",
		Checklist: "给予选择即时后果",
	},
	{
		ID:        "blueprint-215",
		Genre:     "heist",
		Phase:     "progress",
		Goal:      "用连续行动检验主人公的方法，突出计划执行",
		Conflict:  "同步推进目标与关系压力，形成忠诚信任",
		Checklist: "让每次得失改变下一步",
	},
	{
		ID:        "blueprint-216",
		Genre:     "heist",
		Phase:     "midpoint",
		Goal:      "制造改变目标理解的重大结果，突出计划执行",
		Conflict:  "提升公开风险或私人风险，形成忠诚信任",
		Checklist: "把主题问题转化为行动",
	},
	{
		ID:        "blueprint-217",
		Genre:     "heist",
		Phase:     "pressure",
		Goal:      "让对手与内在缺陷同时收紧，突出计划执行",
		Conflict:  "减少可用资源与退路，形成忠诚信任",
		Checklist: "迫使关系承担剧情功能",
	},
	{
		ID:        "blueprint-218",
		Genre:     "heist",
		Phase:     "crisis",
		Goal:      "让旧方法彻底失效并暴露代价，突出计划执行",
		Conflict:  "要求主人公承认真实需求，形成忠诚信任",
		Checklist: "把最终选择准备充分",
	},
	{
		ID:        "blueprint-219",
		Genre:     "heist",
		Phase:     "climax",
		Goal:      "用主动选择解决核心对抗，突出计划执行",
		Conflict:  "让能力成长体现在行动中，形成忠诚信任",
		Checklist: "回收关键伏笔与关系承诺",
	},
	{
		ID:        "blueprint-220",
		Genre:     "heist",
		Phase:     "resolution",
		Goal:      "展示新秩序及其具体差异，突出计划执行",
		Conflict:  "交代主要关系的最终状态，形成忠诚信任",
		Checklist: "用末尾意象回应开场",
	},
	{
		ID:        "blueprint-221",
		Genre:     "biographical",
		Phase:     "opening-image",
		Goal:      "用可视化日常建立主人公当前秩序，突出关键转折",
		Conflict:  "展示尚未解决的核心缺口，形成公共影响",
		Checklist: "让环境细节暗示主题",
	},
	{
		ID:        "blueprint-222",
		Genre:     "biographical",
		Phase:     "inciting-event",
		Goal:      "用不可逆事件打破原有平衡，突出关键转折",
		Conflict:  "迫使主人公回应外部变化，形成公共影响",
		Checklist: "确保事件与核心欲望相关",
	},
	{
		ID:        "blueprint-223",
		Genre:     "biographical",
		Phase:     "debate",
		Goal:      "让主人公比较行动与逃避的代价，突出关键转折",
		Conflict:  "通过关系冲突暴露恐惧，形成公共影响",
		Checklist: "建立进入新局面的必要性",
	},
	{
		ID:        "blueprint-224",
		Genre:     "biographical",
		Phase:     "threshold",
		Goal:      "让主人公做出明确且可见的选择，突出关键转折",
		Conflict:  "改变地点关系或行动规则，形成公共影响",
		Checklist: "给予选择即时后果",
	},
	{
		ID:        "blueprint-225",
		Genre:     "biographical",
		Phase:     "progress",
		Goal:      "用连续行动检验主人公的方法，突出关键转折",
		Conflict:  "同步推进目标与关系压力，形成公共影响",
		Checklist: "让每次得失改变下一步",
	},
	{
		ID:        "blueprint-226",
		Genre:     "biographical",
		Phase:     "midpoint",
		Goal:      "制造改变目标理解的重大结果，突出关键转折",
		Conflict:  "提升公开风险或私人风险，形成公共影响",
		Checklist: "把主题问题转化为行动",
	},
	{
		ID:        "blueprint-227",
		Genre:     "biographical",
		Phase:     "pressure",
		Goal:      "让对手与内在缺陷同时收紧，突出关键转折",
		Conflict:  "减少可用资源与退路，形成公共影响",
		Checklist: "迫使关系承担剧情功能",
	},
	{
		ID:        "blueprint-228",
		Genre:     "biographical",
		Phase:     "crisis",
		Goal:      "让旧方法彻底失效并暴露代价，突出关键转折",
		Conflict:  "要求主人公承认真实需求，形成公共影响",
		Checklist: "把最终选择准备充分",
	},
	{
		ID:        "blueprint-229",
		Genre:     "biographical",
		Phase:     "climax",
		Goal:      "用主动选择解决核心对抗，突出关键转折",
		Conflict:  "让能力成长体现在行动中，形成公共影响",
		Checklist: "回收关键伏笔与关系承诺",
	},
	{
		ID:        "blueprint-230",
		Genre:     "biographical",
		Phase:     "resolution",
		Goal:      "展示新秩序及其具体差异，突出关键转折",
		Conflict:  "交代主要关系的最终状态，形成公共影响",
		Checklist: "用末尾意象回应开场",
	},
	{
		ID:        "blueprint-231",
		Genre:     "experimental",
		Phase:     "opening-image",
		Goal:      "用可视化日常建立主人公当前秩序，突出形式探索",
		Conflict:  "展示尚未解决的核心缺口，形成观众参与",
		Checklist: "让环境细节暗示主题",
	},
	{
		ID:        "blueprint-232",
		Genre:     "experimental",
		Phase:     "inciting-event",
		Goal:      "用不可逆事件打破原有平衡，突出形式探索",
		Conflict:  "迫使主人公回应外部变化，形成观众参与",
		Checklist: "确保事件与核心欲望相关",
	},
	{
		ID:        "blueprint-233",
		Genre:     "experimental",
		Phase:     "debate",
		Goal:      "让主人公比较行动与逃避的代价，突出形式探索",
		Conflict:  "通过关系冲突暴露恐惧，形成观众参与",
		Checklist: "建立进入新局面的必要性",
	},
	{
		ID:        "blueprint-234",
		Genre:     "experimental",
		Phase:     "threshold",
		Goal:      "让主人公做出明确且可见的选择，突出形式探索",
		Conflict:  "改变地点关系或行动规则，形成观众参与",
		Checklist: "给予选择即时后果",
	},
	{
		ID:        "blueprint-235",
		Genre:     "experimental",
		Phase:     "progress",
		Goal:      "用连续行动检验主人公的方法，突出形式探索",
		Conflict:  "同步推进目标与关系压力，形成观众参与",
		Checklist: "让每次得失改变下一步",
	},
	{
		ID:        "blueprint-236",
		Genre:     "experimental",
		Phase:     "midpoint",
		Goal:      "制造改变目标理解的重大结果，突出形式探索",
		Conflict:  "提升公开风险或私人风险，形成观众参与",
		Checklist: "把主题问题转化为行动",
	},
	{
		ID:        "blueprint-237",
		Genre:     "experimental",
		Phase:     "pressure",
		Goal:      "让对手与内在缺陷同时收紧，突出形式探索",
		Conflict:  "减少可用资源与退路，形成观众参与",
		Checklist: "迫使关系承担剧情功能",
	},
	{
		ID:        "blueprint-238",
		Genre:     "experimental",
		Phase:     "crisis",
		Goal:      "让旧方法彻底失效并暴露代价，突出形式探索",
		Conflict:  "要求主人公承认真实需求，形成观众参与",
		Checklist: "把最终选择准备充分",
	},
	{
		ID:        "blueprint-239",
		Genre:     "experimental",
		Phase:     "climax",
		Goal:      "用主动选择解决核心对抗，突出形式探索",
		Conflict:  "让能力成长体现在行动中，形成观众参与",
		Checklist: "回收关键伏笔与关系承诺",
	},
	{
		ID:        "blueprint-240",
		Genre:     "experimental",
		Phase:     "resolution",
		Goal:      "展示新秩序及其具体差异，突出形式探索",
		Conflict:  "交代主要关系的最终状态，形成观众参与",
		Checklist: "用末尾意象回应开场",
	},
}

func Blueprints() []SceneBlueprint {
	return append([]SceneBlueprint(nil), sceneBlueprints...)
}

func ForGenre(genre string) []SceneBlueprint {
	needle := strings.ToLower(strings.TrimSpace(genre))
	out := make([]SceneBlueprint, 0)
	for _, item := range sceneBlueprints {
		if item.Genre == needle {
			out = append(out, item)
		}
	}
	return out
}

func Search(term string) []SceneBlueprint {
	needle := strings.ToLower(strings.TrimSpace(term))
	if needle == "" {
		return Blueprints()
	}
	out := make([]SceneBlueprint, 0)
	for _, item := range sceneBlueprints {
		haystack := strings.ToLower(item.Genre + " " + item.Phase + " " + item.Goal + " " + item.Conflict + " " + item.Checklist)
		if strings.Contains(haystack, needle) {
			out = append(out, item)
		}
	}
	return out
}

func Genres() []string {
	seen := make(map[string]bool)
	out := make([]string, 0)
	for _, item := range sceneBlueprints {
		if !seen[item.Genre] {
			seen[item.Genre] = true
			out = append(out, item.Genre)
		}
	}
	return out
}
